# Generated by Django 6.0.3 on 2026-03-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
